"""Alembic environment — async variant for SQLAlchemy 2.x + asyncmy.

Key differences from the default sync env.py generated by `alembic init`:
1. Uses `async_engine_from_config` (not `engine_from_config`).
2. Wraps migration execution in `asyncio.run()`.
3. Uses `NullPool` so Alembic does not hold an async connection pool.
4. DSN comes from `Settings.database_url` (env var) — not from alembic.ini.
5. `target_metadata = Base.metadata` enables `--autogenerate` diff detection.

Usage (inside the api container):
    alembic upgrade head
    alembic revision --autogenerate -m "add users table"
    alembic downgrade -1
"""

import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context

# ---------------------------------------------------------------------------
# Load Alembic config (alembic.ini)
# ---------------------------------------------------------------------------

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ---------------------------------------------------------------------------
# Import Base and all models so autogenerate can detect schema changes.
# Importing Base alone is not enough — each model module must be imported
# so its mapper is registered with Base.metadata before Alembic compares.
# ---------------------------------------------------------------------------

from app.database import Base  # noqa: E402
from app.notes.models import Note  # noqa: E402, F401  # registers Note with Base.metadata

target_metadata = Base.metadata

# ---------------------------------------------------------------------------
# Override the DSN from Settings (env var) rather than alembic.ini.
# This means DATABASE_URL must be set in the environment when running Alembic.
# ---------------------------------------------------------------------------

from app.core.config import settings  # noqa: E402

config.set_main_option("sqlalchemy.url", settings.database_url)


# ---------------------------------------------------------------------------
# Offline mode — generates SQL script without a live DB connection.
# Useful for reviewing migrations before applying them.
# ---------------------------------------------------------------------------


def run_migrations_offline() -> None:
    """Run migrations without a real DB connection (--sql mode)."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


# ---------------------------------------------------------------------------
# Online mode — async engine; used for `alembic upgrade head` etc.
# ---------------------------------------------------------------------------


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Create an async engine and run migrations inside a sync connection wrapper."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # no pool — Alembic is a one-shot tool
    )
    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
    await connectable.dispose()


def run_migrations_online() -> None:
    """Entry point for online migrations — delegates to asyncio.run."""
    asyncio.run(run_async_migrations())


# ---------------------------------------------------------------------------
# Dispatch: Alembic calls this module; we pick offline vs online.
# ---------------------------------------------------------------------------

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
